### ISSUE TITLE
Exception in thread "main" java.lang.NullPointerException

### ISSUE THREAD

**Issue by RyanMcCarl** [paultopia/cleanup-case#2]
```
$ ./cleancase test.rtf

Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at java.util.regex.Pattern.split(Pattern.java:1206)
	at clojure.string$split.invokeStatic(string.clj:226)
	at clojure.string$split.invoke(string.clj:219)
	at cleanup_case.core$split_opinion.invokeStatic(core.clj:11)
	at cleanup_case.core$split_opinion.invoke(core.clj:9)
	at cleanup_case.core$trees_from_string.invokeStatic(core.clj:29)
	at cleanup_case.core$trees_from_string.invoke(core.clj:27)
	at cleanup_case.core$_main.invokeStatic(core.clj:69)
	at cleanup_case.core$_main.invoke(core.clj:66)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at cleanup_case.core.main(Unknown Source)
```

I have the latest version of JRE (installed today):

```
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by paultopia** [comment]
Oh that's really annoying.  I haven't looked at this in a while, I'll poke around and figure out what happened---might just need a version bump.  

---
Paul Gowder 
http://paul-gowder.com

My book: The Rule of Law in the Real World
http://rulelaw.net

**Comment by paultopia** [comment]
hmm.  actually, what's in test.rtf?  Also, you're on a mac, right?

**Comment by paultopia** [comment]
(I ask what's in test.rtf because it occurs to me, looking back at the code, that I have basically no error handling in here.  My guess is that the null pointer exception is coming from the fact that test.rtf doesn't have the content that I'm expecting---or the call to an osx system utility to convert the rtf into html went wrong.  And that if this is sufficiently interesting to other people that it's being used, I might just do a total rewrite to do things like handle bad data...)
